### ISSUE TITLE
User back to login page after successful login

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/deliver#101]
Bug
----

After a successful login attempt, the user is redirected back to the home
page, where he sees the login button.

When you reload that page however, all is fine. So it looks like the page
does not register the login state?

**Comment by nicolasfranck** [comment]
Seems to be due to [SameSite: SameSiteStrictMode](https://github.com/ugent-library/deliver/blob/dev/handlers/auth.go#L37). The biblio-backoffice does not use this cookie setting.

Also, the second time you login (after an explicit logout), all is fine.

**Comment by nics** [comment]
@nicolasfranck will you fix it?
