### ISSUE TITLE
Folder deleted warnings no longer remain visible for the other user

### ISSUE THREAD

**Issue by mietcls** [ugent-library/deliver#108]
# Bug
Folder deleted warnings no longer remain visible for the other user.

When I delete a folder, that someone else can also see, I get a warning on
- The folder overview
- In the folder itself

These warnings need to remain put, as you cannot assume the other person is watching their screen and will see the action.

<img width="661" alt="Screenshot 2024-01-25 at 16 10 33" src="https://github.com/ugent-library/deliver/assets/1572885/343df2f6-eda1-4d9b-ad50-d7169592300f">

![screenshot_2024-01-25_at_16 10 49](https://github.com/ugent-library/deliver/assets/1572885/6dd64b53-d460-462f-b382-8646bfe21388)

**Comment by nicolasfranck** [comment]
So the message is shown at some point, but then disappears, and that other user is not watching his/her screen and therefore cannot know.

**Comment by nics** [comment]
fixed by #112
