### ISSUE TITLE
Make sure user is informed of lost uploads when navigating away, and is empowered in their decision

### ISSUE THREAD

**Issue by mietcls** [ugent-library/deliver#142]
# Enhancement

Make sure user is informed of lost uploads when navigating away, and is empowered in their decision.

When in a folder, and uploading files, you cannot leave the page without losing uploads
- When clicking a link
- When typing `n` to create a new folder

## Implementation suggestion

> Instead I suggest we add a confirm step when leaving the page during uploads. This can be done by adding/removing an event handler for the [beforeunload](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) event.
See suggestion https://github.com/ugent-library/deliver/pull/140#issuecomment-2051878724

### Modal
Based on https://booktower-ugent-ui.vercel.app/styleguide/b-modals.html#component-09-modal-blank-slate

<img width="694" alt="Screenshot 2024-04-26 at 16 23 11" src="https://github.com/ugent-library/deliver/assets/1572885/a34852bd-906a-4fbd-86d9-e1361247013f">

```
<div class="modal-content">
  <div class="modal-body">
    <div class="c-blank-slate c-blank-slate-muted">
      <div class="bc-avatar">
        <i class="if if-alert"></I>
      </div>
      <h4 class="confirm-header">Are you sure that you want to leave the current page?</h4>
      <p class="confirm-content">Your uploads will be cancelled.</p>
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn btn-link" data-bs-dismiss="modal">No, cancel</button>
    <button class="btn btn-danger confirm-proceed" data-bs-dismiss="modal">Yes, leave page and cancel uploads</button
  </div>
</div>
```

**Comment by nicolasfranck** [comment]
@mietcls having a way to inform the user via a `beforeunload` event does not mean we can show a custom dialog to the end user.

![Screenshot 2024-05-22 at 15 03 28](https://github.com/ugent-library/deliver/assets/494636/102ff9cc-04e5-49c7-acae-5b0ff38749f7)

Modern browsers only seem to support this builtin dialog, and they even not let you change the shown message (in order to avoid misusage).

**Comment by mietcls** [comment]
Thanks!
What happens if you click "cancel" or "leave" in this case? Is the user informed of what happens?
What are the options?

**Comment by nicolasfranck** [comment]
@mietcls I believe "cancel" cancels the unload, so uploading report will continue (even though it is probably already doing that without showing you)
