### ISSUE TITLE
upload progress flow scheme

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/deliver#37]
We need to draw a flow scheme to determine how files are uploaded and how reporting is done.

How it works now:

* User clicks "Upload files" and selects one or more files
* Select widget disappears and is replaced by a list of upload blocks, each of them showing the progress. There is a button "cancel upload" (that does not do anything now)
* When all of the files are successfully uploaded, the page reloads

Problems/todo's:

* When an error occurs on server level, the progress bar stalls, and no error is shown
* When an error occurs on client side (client prevent big files from being uploaded), there is no way to report this. Hide progress bar? Hide cancel button? Or use a complete different template for this?
* When any error occurs, either client or server side, the interface just "stops". Upload blocks for successfully uploaded files are automatically removed from the DOM, but those in error remain. Of course I would not suggest automatically reloading when any error occurs, as that would hide the problems. Put a reload button on top somewhere, when that happens? Or always put a reload button on top (so even when all of them succeeded), and disable the auto reload?
* we need a state to show between  "100% uploaded" and "server has processed your file". Otherwise the user sees that the progress bar has reached 100%, but is not moving anymore for a long time, especially with large files.
* how do we sort the files? On uploaded time, in descending order?

**Comment by nics** [comment]
resolved by #54
