### ISSUE TITLE
Add more clear log-in button

### ISSUE THREAD

**Issue by mietcls** [ugent-library/deliver#47]
# Story

Add more clear log-in button.

People could unfortunately not find it. Add it in the toolbar on top, on the right:
https://biblio-backend-ugent-prototype-ugent-library.vercel.app/deliver/landing.html

```
<div class="bc-toolbar bc-toolbar--auto align-items-start">
    <div class="bc-toolbar-left">
        <div class="bc-toolbar-item">
            <h1>Deliver</h1>
            <p class="c-intro">Supporting library services for UGent Librarians.</p>
        </div>
    </div>
    <div class="bc-toolbar-right">
        <div class="bc-toolbar-item text-right">
            <a class="btn btn-primary" href="/deliver/spaces/ibl.html">
                <i class="if if-arrow-right mt-0 ml-2"></I>
                <span class="btn-text mr-2">Log in</span>
            </a>
        </div>
    </div>
</div>
```

**Comment by nicolasfranck** [comment]
Already done in commit https://github.com/ugent-library/deliver/commit/9c5441028de7f118373b262a22db83a19d6fe7cb, file [templates/page.gohtml](https://github.com/ugent-library/deliver/blob/main/templates/page.gohtml#L68)
