### ISSUE TITLE
Create "download all" button

### ISSUE THREAD

**Issue by mietcls** [ugent-library/deliver#48]
# Story

Create "download all" button with expected file size.
This is useful for
- scan-atelier, as sometimes they have 30+ files to download
- everyone, when deliveries get big

## Expected look
<img width="1440" alt="Scherm­afbeelding 2023-06-23 om 13 35 17" src="https://github.com/ugent-library/deliver/assets/1572885/b8bedffc-4703-492d-9912-34d6bdf91e35">

https://biblio-backend-ugent-prototype-git-feature-3a9547-ugent-library.vercel.app/deliver/spaces/folders/098R4IUHWAFRS9820904.html

## Implementation suggestion

Inside the right table column header:
```
<th class="table-col-sm-fixed table-col-sm-fixed-right text-end align-middle">
    <div class="c-button-group">
        <button class="btn btn-primary">
            <i class="if if-download"></I>
            <span class="btn-text">Download all files</span>
            <small class="btn-text">&mdash; 3MB</small>
        </button>
    </div>
</th>
```

## Expected behaviour

Open to discuss, could be a ZIP

**Comment by nicolasfranck** [comment]
Possible solution: use "compression 0" when sending zip, to make it more streamable.

Possible problems: timeouts at different levels (traefik, browser)
