### ISSUE TITLE
Unable to close "toast" alert box (only if page is reloaded)

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/deliver#53]
<img width="724" alt="Screenshot 2023-02-20 at 09 04 38" src="https://user-images.githubusercontent.com/494636/220047585-078bcdb1-78ca-433d-91ff-a9a4aadbca35.png">

**Comment by nicolasfranck** [comment]
Note: this happens in branch [file_upload_report](https://github.com/ugent-library/deliver/tree/file_upload_report) (see PR https://github.com/ugent-library/deliver/pull/54) only. Apparently due to this [line](https://github.com/ugent-library/deliver/blob/file_upload_report/assets/js/bootstrap.js#L6)

```
export default function() {
  htmx.onLoad(function(el) {
    BSN.initCallback()
  });
}
```

which probably interferes with toast? Apparently htmx onload event is also called on page load for the element "body".

**Comment by nics** [comment]
can't reproduce
