### ISSUE TITLE
Make sure files are downloaded instead of opened in the browser when possible.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/deliver#7]
# Story

Make sure files are downloaded instead of opened in the browser when possible.

Sometimes, especially less-experienced people, are confused by the fact some files open in their browser. This could be mitigated with a download all button when they call helpdesk again.

## Expected behaviour

- [ ] When I click "download", the browser downloads the file

**Comment by nicolasfranck** [comment]
I would indeed opt to force a download to disk (with `Content-Disposition: attachment`) to avoid that confusion.
And then hope that they've seen it (not all browsers show a popup).

About the "download all": that requires a (live) zip download (which may be slow and memory intensive to generate), or rather a list of downloads in sequence (which is often blocked by a browser as seen as "adds")?
