### ISSUE TITLE
Turbo experiment: see your colleague's actions

### ISSUE THREAD

**Issue by mietcls** [ugent-library/deliver#70]
# Experiment

Turbo experiment: see your colleague's actions.
Value: know the world has changed live, don't land on dead pages by accident

Ideas:

_"As a librarian, whenever I am logged in, I can see what my colleagues do live inside folders and with files:"_

Folders:
- [x] When I am in the folder overview, I can see new folders being created
Copy: _Your colleague [Colleague Name] just created the folder [FolderName]._
Toaster type:
- [x] When I am in the folder overview, I can see folders being renamed
Copy: _Your colleague [Colleague Name] just renamed the folder [FolderName] to [NewfolderName]._
Toaster type:
- [x] When I am in the folder overview, I can see folders being deleted
Copy: _Your colleague [Colleague Name] just deleted the folder [Folder Name] and all its files._
Toaster type:

Files:
- [x] When I am *inside the same folder as a colleague*, I can see when files are being added by my colleague
Copy: _Your colleague [Colleague Name] just added the file [FileName] to this folder._
Toaster type:
- [x] When I am *inside the same folder as a colleague*, I can see when files are being deleted by my colleague
Copy: _Your colleague [Colleague Name] just deleted the file [FileName] to this folder._
Toaster type:

## Example

![Scherm­afbeelding 2023-03-29 om 11 45 21](https://user-images.githubusercontent.com/1572885/228495173-cdd54a8f-a486-4d91-ab13-0a440e65b49e.png)

### Success toaster

```
<div class="toast show" role="alert" aria-live="assertive" aria-atomic="true" data-autohide="false">
    <div class="toast-body">
        <i class="if if--primary if-info-circle-filled"></i>
        <div class="toast-content">
            <p>Your colleague [Colleague Name] just [action] ...</p>
        </div>
        <button class="close" type="button" data-dismiss="toast" aria-label="Close">
            <i class="if if-close"></i>
        </button>
    </div>
</div>

```
### Alert toaster

```
<div class="toast show" role="alert" aria-live="assertive" aria-atomic="true" data-autohide="false">
    <div class="toast-body">
        <i class="if if--error if-error-circle-fill"></i>
        <div class="toast-content">
            <p>Your colleague [Colleague Name] just [action] ...</p>
        </div>
        <button class="close" type="button" data-dismiss="toast" aria-label="Close">
            <i class="if if-close"></i>
        </button>
    </div>
</div>
```

### Positioning

![Scherm­afbeelding 2023-03-29 om 11 42 30](https://user-images.githubusercontent.com/1572885/228494355-77c8237e-4a29-4966-bd14-f6ed44409b19.png)

### Component

Toaster: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-toasts.html#component-04-b-toast-simple

**Comment by mietcls** [comment]
@nics here's an idea, please yell if this needs clarification / extra info / simplification

**Comment by mietcls** [comment]
**What works:**

- Seeing a message when a folder is deleted
  - In the folder
  - In the folder overview

  I do fear people are going to miss the message if they are looking away briefly.
  - I can make an improvement issue that it shows as a static alert + interaction to move to the folder overview.
  - Or we can make the toaster not disappear (only to be removed with the X).

**Bugs:**

Folders
- `not sure if in scope` Seeing the folder disappear when your colleague deletes it
- `not sure if in scope` I cannot see the folder name change when my colleague edits it live (not in the overview and not in the folder)
- `not sure if in scope` I can not see folders appear when a colleague adds it

Files
- I cannot see files added by my colleague live
- I cannot see files deleted by my colleague live

Downloads `was not in scope, but documenting here`
- Seeing the download counter go up (see video)
  - When person A downloads a file, person B sees the counter go up
  - When person A downloads a file, person A can not see the counter go up

https://user-images.githubusercontent.com/1572885/234586991-975b47d4-1c31-4c3b-9687-9f0c9933527b.mov

**Comment by nics** [comment]
Only download counter and alert if folder deleted are implemented now

**Comment by mietcls** [comment]
Okay, then the only thing that needs another look is the download counter, optionally the alert duration. The rest is out of scope.

**Comment by nics** [comment]
@mietcls I'll remove the autohide from that alert
