### ISSUE TITLE
Turbo experiment: see when a folder is about to expire + total file download counter

### ISSUE THREAD

**Issue by mietcls** [ugent-library/deliver#71]
# Experiment

Turbo experiment: see when a folder is about to expire + total file download counter
Value: predict whether people will be getting in touch again later to ask for files

## Suggestion

![Scherm­afbeelding 2023-03-29 om 11 55 07](https://user-images.githubusercontent.com/1572885/228497830-d3e075ac-bc26-4f15-9953-4400348a7660.png)

### See which folder is about to expire
![Scherm­afbeelding 2023-03-29 om 11 55 21](https://user-images.githubusercontent.com/1572885/228497899-eb034f2a-4219-42c5-922c-1d655cdbe22a.png)

```
<p class="badge badge-pill badge-default mt-2">
  <i class="if if-info-circle"></I>
  <span class="badge-text">Expires in 2 days.</span>
</p>
```

### See how many file downloads each folder has in total
![Scherm­afbeelding 2023-03-29 om 11 55 28](https://user-images.githubusercontent.com/1572885/228497932-44b625c9-e985-4743-9b02-973d37972044.png)

```
<ul class="c-meta-list c-meta-list-horizontal">
    <li class="c-meta-item">
        <span>0 B</span>
    </li>
    <li class="c-meta-item">
        <span>0 downloads</span>
    </li>
</ul>
```

### Components

Badge: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-badges.html#component-01-b-badge-text
Meta list: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/c-meta-list.html#component-02-c-meta-list-horizontal

**Comment by mietcls** [comment]
@nics and another experiment, feel free to go rogue

**Comment by nics** [comment]
still need to add total downloads
