### ISSUE TITLE
Button inside table: outlines broken after bootstrap update

### ISSUE THREAD

**Issue by mietcls** [ugent-library/deliver#82]
# Bug description
Button inside table: outlines broken after bootstrap update

Button inside table (firefox only):
![Scherm­afbeelding 2023-06-13 om 09 34 29](https://github.com/ugent-library/deliver/assets/1572885/cc1f1911-4149-4a82-8593-69a77da87404)

**Comment by verheyenkoen** [comment]
@mietcls This already seems to be fixed? Tested in Firefox 123 and 124.

![image](https://github.com/ugent-library/deliver/assets/599538/f6047f74-4d16-41a5-9cdc-5726103c65c9)

**Comment by mietcls** [comment]
Ah yes indeed, thanks.
