### ISSUE TITLE
[Speed and usability] Add pagination to folder overview

### ISSUE THREAD

**Issue by mietcls** [ugent-library/deliver#91]
# Enhancement
Add pagination to folder overview.

<img width="940" alt="Screenshot 2023-12-07 at 15 45 08" src="https://github.com/ugent-library/deliver/assets/1572885/53f80c84-f3bd-4dee-b141-06a38c541081">

## Success criteria
- [ ] The page load is lowered by adding pagination and limiting the pages to 20 folders per page
- [ ] I can see how many folders there are on the current page
- [ ] I can see the total of (filtered) folders there are
- [ ] The information is available in the header and footer
- [ ] The pagination works like our other applications (navigation, seeing where you are, truncation)

A few pages:
<img width="362" alt="Screenshot 2023-12-07 at 15 54 34" src="https://github.com/ugent-library/deliver/assets/1572885/009bd080-7cd2-450d-bb7a-9bab03b81508">

A lot of pages
<img width="335" alt="Screenshot 2023-11-24 at 15 03 23" src="https://github.com/ugent-library/deliver/assets/1572885/2b98acc1-2fb4-47d8-a9a1-bf5d7219fe44">

### Implementation
https://biblio-backend-ugent-prototype-ugent-library.vercel.app/deliver/spaces/ibl.html
<img width="940" alt="Screenshot 2023-12-07 at 15 45 08" src="https://github.com/ugent-library/deliver/assets/1572885/53f80c84-f3bd-4dee-b141-06a38c541081">

- To recreate the footer; replace `card-header` with `card-footer`
- See #92 for blank state

```
<div class="card-header">
    <div class="bc-toolbar">
        <div class="bc-toolbar-left">
            <div class="bc-toolbar-item">
                <nav>
                    <ul class="pagination">
                        <li class="page-item disabled">
                            <a class="page-link" href="#" aria-label="Previous">
                                <i class="if if-chevron-left" aria-hidden="true"></i>
                            </a>
                        </li>
                        <li class="page-item active">
                            <a class="page-link" href="#">1</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">2</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#" aria-label="Next">
                                <i class="if if-chevron-right" aria-hidden="true"></i>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="bc-toolbar-item">
                <span class="text-muted c-body-small">Showing 1-20 of 126 folders</span>
            </div>
        </div>
    </div>
</div>
```

### Dependencies and context
Folder overview in spaces have become quite slow for some users when there are many folders (e.g. IBL).

- Depends on #92 (We also need search, as ctrl+f will not work any longer)
- Depends on https://github.com/ugent-library/deliver/issues/73 for ease-of-use

**Comment by nics** [comment]
@mietcls also depends on search? ctrl-f doesn't help you anymore

**Comment by mietcls** [comment]
Good point, will add
