### ISSUE TITLE
[epic] Speed and usability optimisations 

### ISSUE THREAD

**Issue by mietcls** [ugent-library/deliver#93]
# Epic
Speed and search usability optimisations; spaces with a lot of folders take a long time to load.

## Stories
- [x] #91 
- [x] #92
- [x] #73

### Search, sort & pagination
View at https://biblio-backend-ugent-prototype.vercel.app/deliver/spaces/ibl.html
![Screenshot 2023-12-08 at 09 04 52](https://github.com/ugent-library/deliver/assets/1572885/50a62013-aea5-47c6-9846-a0aa66651671)
![Screenshot 2023-12-08 at 09 04 58](https://github.com/ugent-library/deliver/assets/1572885/f98e0ee9-191d-4519-9d4a-6d1c2103879c)

**Comment by verheyenkoen** [comment]
@mietcls This is complete now?

**Comment by mietcls** [comment]
@verheyenkoen yes! I see you've added a clearing functionality to the search, seems like a good idea to align this in the Biblio back office and make the pattern available in our prototype?
