### ISSUE TITLE
Javascript error after deleting a folder

### ISSUE THREAD

**Issue by verheyenkoen** [ugent-library/deliver#99]
After deleting a folder, the Bootstrap framework throws an error (that blocks Cypress tests from succeeding):

<img width="875" alt="image" src="https://github.com/ugent-library/deliver/assets/599538/b00bfa7c-d44b-418f-8949-1a90ded24294">

**Comment by nicolasfranck** [comment]
@verheyenkoen Do you have an example? Deleting a folder works on my end.

**Comment by verheyenkoen** [comment]
In the DevTools console settings, make sure to check "Preserve log" or it will be cleared when the next page loads and you won't see the error.

<img width="610" alt="image" src="https://github.com/ugent-library/deliver/assets/599538/7b798604-c047-4bc0-b9b6-9471e0a7d003">
